### ISSUE TITLE
アイコン作る

### ISSUE THREAD

**Issue by tokku5552** [tokku5552/favotify#28]
## タスク

- アイコン作る

### 資料

- 資料

### 作業

- [ ] アイコン作る

### 完了条件

- 完了条件

**Comment by klsh1tt** [comment]
![favicon](https://user-images.githubusercontent.com/8418485/234761113-2d3abf0e-5943-4298-89bb-4ecce7ef567f.png)
![icon_text](https://user-images.githubusercontent.com/8418485/234761172-f78fc48a-0b01-4a06-8a0e-03edfaaca9f9.png)
